-- FlowBoard initial schema.
--
-- Conventions:
--   * IDs are UUIDv4 strings generated by the application.
--   * All timestamps are INTEGER epoch milliseconds (UTC).
--   * Ordering uses a dense 0..n-1 INTEGER position that is rewritten inside a
--     transaction whenever a card or column moves. Dense positions keep the
--     drag-and-drop math trivial and avoid fractional-index drift.

CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE COLLATE NOCASE,
    name          TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    avatar_color  TEXT NOT NULL DEFAULT '#6366f1',
    created_at    INTEGER NOT NULL,
    updated_at    INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at INTEGER NOT NULL,
    revoked_at INTEGER,
    user_agent TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE IF NOT EXISTS boards (
    id          TEXT PRIMARY KEY,
    owner_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title       TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    color       TEXT NOT NULL DEFAULT 'indigo',
    starred     INTEGER NOT NULL DEFAULT 0,
    archived    INTEGER NOT NULL DEFAULT 0,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_boards_owner ON boards (owner_id, archived);

CREATE TABLE IF NOT EXISTS board_members (
    board_id   TEXT NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role       TEXT NOT NULL DEFAULT 'editor',
    created_at INTEGER NOT NULL,
    PRIMARY KEY (board_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_board_members_user ON board_members (user_id);

CREATE TABLE IF NOT EXISTS board_columns (
    id         TEXT PRIMARY KEY,
    board_id   TEXT NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
    title      TEXT NOT NULL,
    color      TEXT NOT NULL DEFAULT 'slate',
    wip_limit  INTEGER NOT NULL DEFAULT 0,
    position   INTEGER NOT NULL DEFAULT 0,
    is_done    INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_board_columns_board ON board_columns (board_id, position);

CREATE TABLE IF NOT EXISTS labels (
    id         TEXT PRIMARY KEY,
    board_id   TEXT NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    color      TEXT NOT NULL DEFAULT 'slate',
    created_at INTEGER NOT NULL,
    UNIQUE (board_id, name)
);

CREATE TABLE IF NOT EXISTS cards (
    id           TEXT PRIMARY KEY,
    board_id     TEXT NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
    column_id    TEXT NOT NULL REFERENCES board_columns (id) ON DELETE CASCADE,
    title        TEXT NOT NULL,
    description  TEXT NOT NULL DEFAULT '',
    position     INTEGER NOT NULL DEFAULT 0,
    priority     INTEGER NOT NULL DEFAULT 1,
    due_date     INTEGER,
    assignee_id  TEXT REFERENCES users (id) ON DELETE SET NULL,
    cover_color  TEXT NOT NULL DEFAULT '',
    archived     INTEGER NOT NULL DEFAULT 0,
    created_by   TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    completed_at INTEGER
);
CREATE INDEX IF NOT EXISTS idx_cards_column ON cards (column_id, position);
CREATE INDEX IF NOT EXISTS idx_cards_board ON cards (board_id, archived);
CREATE INDEX IF NOT EXISTS idx_cards_assignee ON cards (assignee_id);
CREATE INDEX IF NOT EXISTS idx_cards_due ON cards (due_date);

CREATE TABLE IF NOT EXISTS card_labels (
    card_id TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    label_id TEXT NOT NULL REFERENCES labels (id) ON DELETE CASCADE,
    PRIMARY KEY (card_id, label_id)
);
CREATE INDEX IF NOT EXISTS idx_card_labels_label ON card_labels (label_id);

CREATE TABLE IF NOT EXISTS checklist_items (
    id         TEXT PRIMARY KEY,
    card_id    TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    text       TEXT NOT NULL,
    done       INTEGER NOT NULL DEFAULT 0,
    position   INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_checklist_card ON checklist_items (card_id, position);

CREATE TABLE IF NOT EXISTS comments (
    id         TEXT PRIMARY KEY,
    card_id    TEXT NOT NULL REFERENCES cards (id) ON DELETE CASCADE,
    author_id  TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    body       TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_comments_card ON comments (card_id, created_at);

CREATE TABLE IF NOT EXISTS activity (
    id         TEXT PRIMARY KEY,
    board_id   TEXT NOT NULL REFERENCES boards (id) ON DELETE CASCADE,
    card_id    TEXT REFERENCES cards (id) ON DELETE CASCADE,
    actor_id   TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    verb       TEXT NOT NULL,
    summary    TEXT NOT NULL DEFAULT '',
    created_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_activity_board ON activity (board_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_card ON activity (card_id, created_at DESC);
